'use strict';mix_d("PrimeAcquisitionCXCards__pin-flyout-desktop-card:pin-flyout-desktop-card__ykA7eWST",["exports","tslib","@c/scoped-dom","@c/aui-untrusted-ajax","@c/logger"],function(w,g,z,A,B){function u(d){return d&&"object"===typeof d&&"default"in d?d:{"default":d}}function x(d,b){return g.__awaiter(this,void 0,void 0,function(){var c;return g.__generator(this,function(e){try{return c={accepts:"application/json",contentType:"application/json;charset=UTF-8",additionalHeaders:C({})},[2,D["default"].post(b,
c,d).then(function(a){(a=a.responseBody.payload.requestSuccess)||l["default"].log("Request the customer name ajax failed","ERROR");return a}).catch(function(a){l["default"].log("An error occurred while publishing metrics",a);return!1})]}catch(a){l["default"].log("Request the customer name ajax failed with the error:"+a,"ERROR")}return[2,!1]})})}function C(d){var b=(b=y["default"].cardRoot.querySelector("meta[name='anti-csrftoken-a2z']"))?b.getAttribute("content"):"";d["anti-csrftoken-a2z"]=b;return d}
var y=u(z),D=u(A),l=u(B),p;(p||(p={})).Count="Count";var E=function(){function d(b){this.endpoint=b.endpoint}d.prototype.publishImpressionMetric=function(b,c,e){var a=p.Count;c=this.getStandardEventData(b,c,e);null===c?l["default"].log("Event data is null and it indicates the DOM associated to the class isn't available","WARN"):this.publishMetric("Impression",1,a,c,b,this.endpoint)};d.prototype.publishButtonClickMetric=function(b,c){var e=this,a=p.Count,f=this.getStandardEventData(b,c);null===f?l["default"].log("Event data is null and it indicates the DOM associated to the class isn't available",
"WARN"):(c=document.querySelectorAll(".".concat(b," button")),0===c.length?l["default"].log("No buttons found for the given class","WARN"):c.forEach(function(h){h.addEventListener("click",function(){e.publishMetric("ButtonClick",1,a,f,b,e.endpoint)})}))};d.prototype.publishSpecificButtonClickMetric=function(b,c,e,a,f){var h=this,m=p.Count,k=this.getStandardEventData(b,a,f);null===k?l["default"].log("Event data is null and it indicates the DOM associated to the class isn't available","WARN"):(a=document.querySelector('[class*="'.concat(c,
'"], [id*="').concat(c,'"]')))?a.addEventListener("click",function(){h.publishMetric(e,1,m,k,b,h.endpoint)}):l["default"].log("Button with selector ".concat(c," not found"),"WARN")};d.prototype.publishCustomMetric=function(b,c,e,a){a=this.extractDimensionsForAdditionalEventData(a);a=Object.fromEntries(a);x({metricName:c,metricValue:e,metricUnit:p.Count,dimensions:a,location:b},this.endpoint)};d.prototype.publishMetric=function(b,c,e,a,f,h){a=this.extractDimensions(a);a=Object.fromEntries(a);x({metricName:b,
metricValue:c,metricUnit:e,dimensions:a,location:f},h)};d.prototype.getStandardEventData=function(b,c,e){return(e=document.querySelector('[class^="'.concat(b,'"], [id^="').concat(b,'"]'))||document.querySelector('div[data-csa-c-painter="'.concat(e,'"]')))?(b={cardName:e.getAttribute("data-csa-c-painter")||b,widgetId:e.getAttribute("data-csa-c-widget-id")||"",pageId:e.getAttribute("data-csa-c-page-id")||"",deviceType:e.getAttribute("data-csa-c-device-type")||""},g.__assign(g.__assign({},b),c)):null};
d.prototype.extractDimensions=function(b){var c,e=new Map;try{for(var a=g.__values(Object.entries(b)),f=a.next();!f.done;f=a.next()){var h=g.__read(f.value,2),m=h[0],k=h[1];"string"!==typeof k&&"number"!==typeof k||""===k.toString()||e.set(m,k.toString())}}catch(q){var n={error:q}}finally{try{f&&!f.done&&(c=a.return)&&c.call(a)}finally{if(n)throw n.error;}}return e};d.prototype.extractDimensionsForAdditionalEventData=function(b){var c,e=new Map;try{for(var a=g.__values(Object.entries(b)),f=a.next();!f.done;f=
a.next()){var h=g.__read(f.value,2),m=h[0],k=h[1];"string"!==typeof k&&"number"!==typeof k||""===k.toString()||e.set(m,k.toString())}}catch(q){var n={error:q}}finally{try{f&&!f.done&&(c=a.return)&&c.call(a)}finally{if(n)throw n.error;}}return e};return d}(),v=function(){function d(){this._state=null}d.getInstance=function(){d.instance||(d.instance=new d);return d.instance};d.prototype.extractMetadata=function(b){var c,e,a,f,h,m,k,n;b=(b.querySelector("[data-csa-c-metadata-map]")||b).getAttribute("data-csa-c-metadata-map");
var q={};if(b)try{var t=JSON.parse(b),r=t.metadataMap?JSON.parse(t.metadataMap):{},F={offerType:null!==(c=r.offerType)&&void 0!==c?c:"NONE",benefitRestrictionType:null!==(e=r.benefitRestrictionType)&&void 0!==e?e:"NONE",offerSegment:null!==(a=r.offerSegment)&&void 0!==a?a:"NONE",feeType:null!==(f=r.feeType)&&void 0!==f?f:"NONE",benefitTier:null!==(h=r.benefitTier)&&void 0!==h?h:"NONE",variantId:null!==(m=r.variantId)&&void 0!==m?m:"NONE"},G={marketingContentCreativeId:null!==(k=t.marketingContentCreativeId)&&
void 0!==k?k:"NONE",acquisitionDevice:null!==(n=t.acquisitionDevice)&&void 0!==n?n:"NONE"};q=g.__assign(g.__assign({},F),G)}catch(H){l["default"].log("Error parsing analyticalMetadataMap:"+H,"ERROR")}return q};d.prototype.initialize=function(b,c,e,a){e=this.extractMetadata(e);this._state={publisher:new E({endpoint:b}),cardName:c,csaAttributes:e,painterId:a}};d.prototype.publishImpression=function(b){var c=this.getState();c.publisher.publishImpressionMetric(c.cardName,g.__assign(g.__assign({},c.csaAttributes),
b),c.painterId)};d.prototype.publishButtonClick=function(b){var c=this.getState();c.publisher.publishButtonClickMetric(c.cardName,g.__assign(g.__assign({},c.csaAttributes),b))};d.prototype.publishSpecificButtonClick=function(b,c,e){var a=this.getState();a.publisher.publishSpecificButtonClickMetric(a.cardName,b,c,g.__assign(g.__assign({},a.csaAttributes),e),a.painterId)};d.prototype.publishCustomMetric=function(b,c,e){var a=this.getState();a.publisher.publishCustomMetric(a.cardName,b,c,g.__assign(g.__assign({cardName:a.cardName},
a.csaAttributes),e))};d.prototype.getState=function(){if(!this._state)throw Error("MetricsService must be initialized before use");return this._state};return d}().getInstance();w._operationNames=[];w.card=function(){return g.__awaiter(void 0,void 0,void 0,function(){var d;return g.__generator(this,function(b){d=y["default"].cardRoot;v.initialize("/prime-ajax/acquisition/metrics","pin-flyout-desktop-card",d,"pin-flyout-desktop-card");v.publishImpression();v.publishSpecificButtonClick("pin-flyout-cta-button",
"pin_flyout_cta_click");return[2]})})}});
