'use strict';mix_d("ZeitgeistListsFrontEndCards__p13n-zg-list-carousel-desktop:p13n-zg-list-carousel-desktop__BGgMJt5R","exports tslib @c/aui-carousel @c/scoped-dom @p/A @c/aui-untrusted-ajax @c/metrics @c/dom @c/remote-operations @p/a-carousel-framework @c/logger @c/browser-operations".split(" "),function(F,q,R,S,T,U,z,V,W,X,Y,Z){function x(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var G=x(R),u=x(S),g=x(T),H=x(U),I=x(W),aa=x(X),A=x(Y),ba=x(Z),J={},C=function(a,c,b){void 0===
c&&(c="");void 0===b&&(b=1);c=a+c;J.hasOwnProperty(c)||(J[c]=!0,z.count(a,(z.count(a)||0)+b))},ca=function(a){C(g["default"].capabilities.mobile?"Card:EERU:SharedLib:mobile:render":"Card:EERU:SharedLib:desktop:render");var c=function(d,e){d={$event:{preventDefault:g["default"].$.noop,stopPropagation:g["default"].$.noop},$target:d.getContent().find('[data-a-tab-name="'+e+'"]'),data:{name:"energyEfficiencyTabSet"}};g["default"].trigger("a:declarative:a-tabs:click",d)},b=function(d,e){var f=d&&d.$event,
h=d&&d.data||{},p=h.activeTabName,m=h.modalHeight,t=h.name;f&&f.preventDefault&&f.preventDefault();f&&f.stopPropagation&&f.stopPropagation();f=e.get(t);f||(g["default"].on("a:popover:beforeShow:"+t,function(k){k.popover&&k.popover.getContent&&(k=k.popover.getContent(),k.find(".a-manually-loaded").parent().css("min-height",m),g["default"].loadDescendantImagesManually(k))}),f=e.create(d.$target,h));f.show();c(f,p)};a.when("a-secondary-view").execute("RegisterEnergyEfficiencyEventMobile",function(d){g["default"].declarative("card-energy-efficiency-secondary-view",
"click",function(e){C("Card:EERU:SharedLib:mobile:click",e&&e.data&&e.data.name||"");b(e,d)})});a.when("a-modal").execute("RegisterEnergyEfficiencyEventDesktop",function(d){g["default"].declarative("card-energy-efficiency-modal","click",function(e){C("Card:EERU:SharedLib:desktop:click",e&&e.data&&e.data.name||"");b(e,d)})})},da=function(a){a.when("ready").execute("EEBadgeProductFicheResize",function(c){var b=g["default"].$;b(".energyEfficiencyContainer").each(function(d,e){d=b(e).find(".energyEfficiencyProductFicheLabel").first();
e=b(e).find("svg").first();d.parent().outerHeight()>e.outerHeight()&&(d.removeClass("a-size-small"),d.addClass("a-size-micro"),d.parent().outerHeight()>e.outerHeight()&&d.parent().css("line-height","10px"))})})},ea={ctiList:["Website/Personalization/Report a Problem CX"],category:"Website",type:"Personalization",item:"Report a Problem CX",folder:"9c9c97c9-6f69-4dba-a55d-26045c6a3068",group:"P13N Report a Problem CX"},fa=[{ctiList:["Website/Personalization/Similarities","Website/Detail Page/Similarities"],
category:"Website",type:"Personalization",item:"Similarities",folder:"4d16d05d-9a17-4b36-b8fe-9ee159ff81de",group:"Similarities"}],ka=function(a){var c=u["default"].cardRoot.querySelector(".p13n-report-flag"),b=ba["default"].setup();b.define("showFlag","mouseover",function(){c.classList.remove("p13n-report-flag-hide")});b.define("hideFlag","mouseout",function(){c.classList.add("p13n-report-flag-hide")});b.attach("showFlag",a);b.attach("hideFlag",a);var d=u["default"].cardRoot.querySelector(".internal-flag-form"),
e=d.querySelector(".internal-flag-env-data").dataset,f=d.querySelector(".internal-flag-title-text"),h=d.querySelector(".internal-flag-description").firstElementChild,p=d.querySelector(".internal-flag-alias"),m=d.querySelector(".internal-flag-response-message"),t=function(k){k.preventDefault();k=function(r){return!r||!r.trim()};if(k(f.value)||k(h.value)||k(p.value))return D(m,!1,"Something went wrong. One of the required fields was missing."),!1;k=u["default"].cardRoot.querySelectorAll(".a-dynamic-image");
var l;if(l=u["default"].cardRoot.querySelector(".a-carousel-heading")){var v=ha(a,k.length);l="Internal user reported issue '"+f.value+"' with widget: "+l.innerText}else v=ia(a),l="Internal user reported issue '"+f.value+"'";k=ja(k,v,h.value,p.value,e);var n=ea;fa.forEach(function(r){r.ctiList.includes(e.cti)&&(n=r)});H["default"].post("https://p13ngoals.corp.amazon.com/sims",{accepts:"text/html, application/json",contentType:"application/json;charset=UTF-8"},{sim_params:{assigned_folder:n.folder,
description:k,descriptionContentType:"text/amz-markdown-sim",extensions:{tt:{assignedGroup:n.group,category:n.category,impact:5,item:n.item,type:n.type}},tags:[{id:"internal-problem-generated"}],title:l}}).then(function(r){D(m,!0,r)}).catch(function(r){D(m,!1,r)});return!1};d.onsubmit=function(k){return t(k)};b=u["default"].cardRoot.querySelector(".p13n-desktop-report-problem-flag-data");if(b.dataset.name)g["default"].on("a:popover:hide:"+b.dataset.name,function(){d.reset();m.innerText=""})},ha=function(a,
c){if(!a.dataset.aCarouselOptions)return A["default"].log("Empty ASIN List in carouselElement.dataset.aCarouselOptions","ERROR"),[];a=JSON.parse(a.dataset.aCarouselOptions).ajax.id_list;var b=u["default"].cardRoot.querySelector(".a-carousel-firstvisibleitem");b=(Number(b.value)||1)-1;return a.map(function(d){return JSON.parse(d).id}).slice(b,b+c)},ia=function(a){return(a=a.dataset.asinList)?a.split(","):[]},ja=function(a,c,b,d,e){for(var f="",h=0;h<a.length;h++){var p=a[h];f+=(p?"![]("+p.src+")":
"IMAGE MISSING")+"\nASIN: "+(c[h]?c[h]:"ASIN MISSING")+"\n\n"}return"**This SIM-T ticket is created by the 'Report a Problem' internal tool. To know more, here's its wiki: https://w.amazon.com/bin/view/Personalization/CoreRecommendations/Projects/Canaries/Report-a-Problem-UX-on-P13NWidget/UserGuide/**\n\n**Alias:** ["+(d+"](https://phonetool.amazon.com/users/"+d+")\n**Comment:** "+b+"\n\n**Widget Group ID:** "+e.widgetGroupId+"\n**Strategy ID:** "+e.strategyId+"\n**CTI:** "+e.cti+"\n**Facets:** ")+
(e.facets+"\n**Content Reftag:** "+e.reftag+"\n"+(""!==e.baseAsin?"**Page ASIN:** "+e.baseAsin+"\n":"")+"\n**SessionID:** ")+(e.sessionId+"\n**MarketplaceID:** "+e.marketplaceId+"\n**Device Type:** "+e.deviceType+"\n\n**List of ASINs:**\n\n")+f},D=function(a,c,b){c?(a.classList.remove("a-color-error"),b.responseBody&&"object"===typeof b.responseBody?b.responseBody.response&&b.responseBody.response.id?a.innerHTML="Success, here's the <a href=\"https://t.corp.amazon.com/"+b.responseBody.response.id+
'" target="_blank">SIM-T ticket</a> you created.':(A["default"].log("Fail to find the id of the SIM-T ticket created in the response body of response data.","ERROR"),a.innerText="Success, but we could not find the link to the SIM-T ticket."):(A["default"].log("The response body of response data is not an object.","ERROR"),a.innerText="Success, but we could not find the link to the SIM-T ticket.")):(a.classList.add("a-color-error"),a.innerText="string"===typeof b?b:"Oops! Something went wrong. Please try again.")},
la={setupModal:function(a){return q.__awaiter(void 0,void 0,void 0,function(){var c;return q.__generator(this,function(b){c=u["default"].cardRoot.querySelector(".p13n-report-problem-modal-root");if(!c)return[2];ka(a);return[2]})})}},ma=I["default"].setup(["getLazyLoadDeliveryMessage"]),na=function(a){return q.__awaiter(void 0,void 0,void 0,function(){var c,b,d;return q.__generator(this,function(e){switch(e.label){case 0:c=a.querySelectorAll("[data-udm-asin]:not([data-requested=true])");if(!c.length)return[2,
void 0];b=[];c.forEach(function(f){var h=f.dataset.udmAsin,p=f.dataset.udmMerchantId,m=f.dataset.udmBlockSize,t=f.dataset.udmLayoutSize,k="true"===f.dataset.udmBadgeWithoutProgramName;h&&p&&m&&(b.push({asin:h,merchantId:p,blockSize:m,layoutSize:t,badgeWithoutProgramName:k}),f.dataset.requested="true")});return b.length?[4,ma.getLazyLoadDeliveryMessage({lazyLoadDeliveryMessageViewModels:b})]:[2,void 0];case 1:return d=e.sent(),[2,[].slice.call(d.querySelectorAll("[data-udm-asin]:not([data-requested=true])"))]}})})},
oa=function(a){return q.__awaiter(void 0,void 0,void 0,function(){var c;return q.__generator(this,function(b){switch(b.label){case 0:return[4,na(a)];case 1:c=b.sent();if(!c)return[2];c.map(function(d){var e=d.dataset.udmAsin,f=d.dataset.udmMerchantId;e&&f&&(e=a.querySelector("[data-udm-asin="+e+"][data-udm-merchant-id="+f+"]"))&&(e.outerHTML=d.innerHTML)});return[2]}})})},K=[],pa=function(a){var c=Array.prototype.slice.call(a.querySelectorAll("[data-metrics]"));c.push(a);c.forEach(function(b){if(b&&
b.dataset&&b.dataset.metrics&&(!b.id||!K.includes(b.id))){var d=JSON.parse(b.dataset.metrics),e;for(e in d)d.hasOwnProperty(e)&&z.count(e,d[e]);b.removeAttribute("data-metrics");b.id&&K.push(b.id)}})},L=/(?=[ \-\/])|(?=[\u3105-\u312F])|(?=[\u31A0-\u31BA])|(?=[\u4E00-\u9FD5])|(?=[\u3400-\u4DB5])|(?=[\uF900-\uFAFF])|(?=[\u3040-\u309F])|(?=[\u30A0-\u30FF])|(?=[\u3190-\u319F])/,M=/[^\/\-\[\]():\s]/,qa=function(a){var c=g["default"].$("<div>")[0];c.classList.add("p13n-sc-offscreen-truncate");var b=parseInt(a.getAttribute("data-rows")||
"2",10),d=function(){var h=a.innerHTML;a.innerHTML="&hellip;";var p=a.clientHeight;a.innerHTML=h;return p}();if(b){if(d){var e=function(h){c.innerHTML=h;return Math.round(c.clientHeight/d)<=b},f=function(h,p){h=h.split(p);var m=Math.floor(a.clientWidth/12),t=function(l){c.classList.add("p13n-sc-offscreen-truncate");c.style.overflow="hidden";c.textContent=l;a.appendChild(c);l=a.clientWidth>=a.scrollWidth;a.removeChild(c);return l},k=function(l){var v=l.length-m;l.trim().length>m&&!t(l)&&Array.prototype.slice.call(l).map(function(n,
r){return r>m&&r<=v&&M.test(n)?"&shy;"+n:n});return l};return h.map(function(l){return k(l)}).join("")};return{truncate:function(){var h=a.innerHTML.trim(),p=a.textContent||"";h=f(h,L);a.appendChild(c);if(e(h))a.removeChild(c),a.innerHTML=h;else{var m=h.split(L);for(var t=1,k=m.length,l,v,n=0;t!==k;)if(l=Math.floor((k+t)/2),v=m.slice(0,l).join("")+"&hellip;",e(v)){if(1>=k-l){for(n=l;0<n&&!M.test(m[n-1]);)n--;break}t=l}else k=l;m=0===n?void 0:m.slice(0,n).join("")+"&hellip;";m?(a.innerHTML=m,a.setAttribute("title",
p),a.setAttribute("aria-label",p)):(A["default"].log("Unable to successfully truncate line "+h,"ERROR"),a.removeChild(c))}}}}A["default"].log("Truncation element does not have a line height or it is zero","ERROR")}else A["default"].log("Truncation element missing necessary line number data","ERROR")},ra=function(a){var c=Array.prototype.slice.call(a.getElementsByClassName("p13n-sc-truncate"));a=a.getElementsByClassName("p13n-sc-truncate-fallback");(window.CSS&&CSS.supports&&CSS.supports("-webkit-line-clamp",
"1")?c:c.concat(Array.prototype.slice.call(a))).filter(function(b){return!!b.offsetParent}).map(function(b){var d=qa(b);d&&(d.truncate(),b.classList.add("p13n-sc-truncated"),b.classList.remove("p13n-sc-truncate"),b.classList.remove("p13n-sc-truncate-fallback"),b.className=b.className.replace(/p13n-sc-line-clamp-\d/g,""))})},sa=function(a){a.querySelectorAll(".a-carousel-viewport").forEach(function(c){c=c.querySelectorAll(".a-carousel-card");for(var b=null,d=0;d<c.length;d++){var e=c[d].getAttribute("aria-roledescription");
if(null!==e&&""!==e){b=e;break}}b=b||"slide";c.forEach(function(f){f.getAttribute("aria-roledescription")!==b&&f.setAttribute("aria-roledescription",b)})})},ya={initCarousel:function(a){return q.__awaiter(void 0,void 0,void 0,function(){var c,b,d;return q.__generator(this,function(e){c=(a||{}).afterPageLoaded;b=u["default"].cardRoot.classList.contains("p13n-sc-shoveler")?[u["default"].cardRoot]:Array.prototype.slice.call(u["default"].cardRoot.getElementsByClassName("p13n-sc-shoveler"));d=I["default"].setup(["getCarouselItems"]);
if(null===b||void 0===b||!b.length)return[2];b.forEach(function(f){return q.__awaiter(void 0,void 0,void 0,function(){var h,p,m,t,k,l;return q.__generator(this,function(v){switch(v.label){case 0:h=f.dataset||{};p="true"===h.showlazyloaddeliverymessage;m=function(){g["default"].loadDynamicImage("[data-name]='"+l+"' .p13n-sc-dynamic-image");ra(f);pa(f);null===c||void 0===c?void 0:c(f);var n=window.P;ca(n);da(n);sa(f);p&&oa(f)};m();if(f.classList.contains("p13n-carousel-initialized"))return[2];f.classList.add("p13n-carousel-initialized");
t=aa["default"].getCarousel(V.unscope(f));k=G["default"].getCarousel(f);l=t.getAttr("name");return[4,Promise.all([k.initialized,la.setupModal(f)])];case 1:return v.sent(),g["default"].on("a:carousel:"+l+":change:pageSize",m),g["default"].on("a:carousel:"+l+":change:loading",m),g["default"].on("a:carousel:"+l+":change:animating",m),g["default"].on("a:carousel:"+l+":change:fetchedItems",m),k.attachRemoteOperation(function(n){var r=n.indexes;n=n.ids;var N=d,ta=N.getCarouselItems,ua=q.__assign,va=q.__assign({},
h),wa=String(r[0]||0);var xa=r[0]||0,y,E,O=0,w=h.aCarouselOptions?h.aCarouselOptions:void 0;if(w&&(w=JSON.parse(w),w=null===(y=null===w||void 0===w?void 0:w.ajax)||void 0===y?void 0:y.id_list))for(y=0;y<xa&&y<w.length;y++){var B=JSON.parse(w[y]);"true"===((null===(E=null===B||void 0===B?void 0:B.metadataMap)||void 0===E?0:E.isSponsoredProduct)?B.metadataMap.isSponsoredProduct:"false")&&(O+=1)}return ta.call(N,ua.call(q,va,{ids:n,indexes:r,offset:wa,adOffset:O}))}),[2]}})})});return[2]})})}},za=function(a){var c=
q.__assign(q.__assign(q.__assign({adaptiveWidgetContext:{asinList:g["default"].$(a.widgetSelector+" [data-asin]").map(function(){return g["default"].$(this).attr("data-asin")}).get().filter(function(b){return void 0!==b&&null!==b&&""!==b}),widgetSelector:a.widgetSelector,adaptiveVideoElements:g["default"].$(a.widgetSelector+" [data-product-asin]").map(function(){return{title:g["default"].$(this).attr("data-title"),vendorName:g["default"].$(this).attr("data-vendor-name"),contentId:g["default"].$(this).attr("data-content-id"),
videoUrl:g["default"].$(this).attr("data-video-url"),productAsin:g["default"].$(this).attr("data-product-asin"),groupType:g["default"].$(this).attr("data-group-type"),videoHeight:g["default"].$(this).attr("data-video-height"),videoWidth:g["default"].$(this).attr("data-video-width"),closedCaptions:g["default"].$(this).attr("data-closed-captions"),vendorTrackingId:g["default"].$(this).attr("data-vendor-tracking-id"),videoReferenceId:g["default"].$(this).attr("data-video-reference-id"),aciContentId:g["default"].$(this).attr("data-aci-content-id"),
profileUrl:g["default"].$(this).attr("data-profile-url"),profileAvatarUrl:g["default"].$(this).attr("data-profile-avatar-url")}}).get().filter(function(b){return void 0!==b&&null!==b&&""!=b.productAsin})},clientPrefix:a.clientPrefix,page:a.page,placement:a.placement,device:g["default"].capabilities.mobile?"Mobile":"Desktop",product:{contentID:g["default"].$(a.widgetSelector).find("[data-asin]").attr("data-asin"),contentIDType:"ASIN"}},a.reftag?{metadata:{reftag:a.reftag}}:{}),a.linkParams?{metadata:{celQueryStringParam:Array.from(a.linkParams.entries()).map(function(b){b=
q.__read(b,2);var d=b[1];return"".concat(b[0],"=").concat(d)}).join("&")}}:{}),{needPlayerFactory:a.needPlayerFactory||!1});0===c.adaptiveWidgetContext.asinList.length?z.count(c.clientPrefix+":adaptiveVideosCannotFindAsinList",1):P(c,function(b){g["default"].$(a.widgetSelector).find(a.responsePlaceholderSelector).first().html(b.responseBody);g["default"].$(a.widgetSelector).addClass("ive-aw-has-video")})},Aa=function(a){var c;g["default"].delay(function(){g["default"].trigger("ive:".concat(a.clientPrefix,
":adaptiveWidget:update"))},null!==(c=a.updateDelay)&&void 0!==c?c:60)},P=function(a,c,b){void 0===b&&(b=3);b--;H["default"].post("/vap/ew/componentbuilder",{accepts:"*/*",contentType:"application/json;charset=UTF-8",timeout:5E3},a).then(function(d){c(d);z.count(a.clientPrefix+":adaptiveVideosComponentBuilderSuccess",1)}).catch(function(){0<b?P(a,c,b):z.count(a.clientPrefix+":adaptiveVideosComponentBuilderFailed",1)})},Q=function(a){var c,b="#"+u["default"].cardRoot.id,d=null!==(c=g["default"].$(b).parent().attr("cel_widget_id"))&&
void 0!==c?c:"bestsellers";a={widgetSelector:b,page:"BestSellers",placement:a,clientPrefix:d,responsePlaceholderSelector:"#videoResponsePlaceholder"};u["default"].cardRoot.classList.contains("ive-aw-has-video")?Aa(a):za(a)},Ba=function(a){if(null!==u["default"].cardRoot.querySelector("#videoResponsePlaceholder")){Q(a);var c=u["default"].cardRoot.getElementsByClassName("p13n-sc-shoveler");if(0<c.length)G["default"].getCarousel(c[0]).on("change:pageNumber",function(){Q(a)})}};F._operationNames=["getCarouselItems"];
F.card=function(){return q.__awaiter(void 0,void 0,void 0,function(){return q.__generator(this,function(a){switch(a.label){case 0:return[4,ya.initCarousel()];case 1:return a.sent(),Ba("Carousel"),[2]}})})}});
