'use strict';(function(g){var f=window.AmazonUIPageJS||window.P,n=f._namespace||f.attributeErrors,a=n?n("DetailPageProductSpecDepthAsset",""):f;a.guardFatal?a.guardFatal(g)(a,window):a.execute(function(){g(a,window)})})(function(g,f,n){g.when("A","ready","a-toggle-button","voyager-desktop-metric").register("voyager-expand-collapse-module",function(a,e,b,l){function d(){return h("#productDetails_expanderSectionTables").find(".a-expander-header")}function f(c,a){c=b(c);a?c.enable():c.disable()}function c(){var c=
h("#productDetails_expanderSectionTables").find(".a-expander-content");c&&c.length&&(c=c.find(".prodDetSectionEntry"))&&15>c.length&&(d().each(function(){"true"!==this.getAttribute("data-expanded")&&h(this).click()}),f("#voyager-expand-all-btn",!1),f("#voyager-collapse-all-btn",!0))}e=a.state("voyager-desktop-context");var k="unknown",m="unknown";e&&(k=e["voyager-desktop-treatment"],m=e.product_type);var h=a.$;c();a.on("PageRefresh:ATF",c);a.declarative("voyager-expand-all-handler","click",function(){var c=
d();c&&c.length&&(l.incrementCounter(l.metricName.expandAllButtonClicked(m,k)),l.incrementCounter(l.metricName.expandAllButtonClicked("all","all")),c.each(function(){"true"!==this.getAttribute("aria-expanded")&&h(this).click()}))});a.declarative("voyager-collapse-all-handler","click",function(){var c=d();c&&c.length&&(l.incrementCounter(l.metricName.collapseAllButtonClicked(m,k)),l.incrementCounter(l.metricName.collapseAllButtonClicked("all","all")),c.each(function(){"true"===this.getAttribute("aria-expanded")&&
h(this).click()}))});a.declarative("voyager-expander-heading-toggle","click",function(){var c=!1,b=!1;d().each(function(){"true"===this.getAttribute("aria-expanded")?b=!0:c=!0});f("#voyager-expand-all-btn",c);f("#voyager-collapse-all-btn",b)})});"use strict";g.when("A","ready").register("voyager-pd-desktop-jump-link",function(a){function e(){var b=a.$("#seeMoreDetailsLink"),e=a.$("#productDetails_expanderSectionTables");b.length&&e.length&&b.parent().removeClass("aok-hidden")}e();a.on("a:pageUpdate",
e)});"use strict";"use strict";"use strict";"use strict";"use strict";"use strict";"use strict";"use strict";g.when("A","ready").register("voyager-desktop-metric",function(a){a={};a={impression:function(a,b){return"voyager:desktop:"+a+":"+b+":impression"},sectionExpanderClicked:function(a,b,f,d){return"voyager:desktop:"+a+":"+b+":"+f+":"+d+":clicked"},sectionExpanderOverallClicked:function(a,b){return"voyager:desktop:"+a+":"+b+":sectionExpander:overall:clicked"},expandAllButtonClicked:function(a,
b){return"voyager:desktop:"+a+":"+b+":expandAll:clicked"},collapseAllButtonClicked:function(a,b){return"voyager:desktop:"+a+":"+b+":collapseAll:clicked"},sectionExpanderContentDwellTime:function(a,b,f,d){return"voyager:desktop:"+a+":"+b+":"+f+":"+d+":dwellTime"},sectionExpanderContentOverallDwellTime:function(a,b){return"voyager:desktop:"+a+":"+b+":sectionExpander:overall:dwellTime"}};return{incrementCounter:function(a){f.ue&&f.ue.count&&f.ue.count(a,(f.ue.count(a)||0)+1)},setCounter:function(a,b){f.ue&&
f.ue.count&&f.ue.count(a,b)},metricName:a}});"use strict";g.when("A","jQuery","voyager-desktop-metric").execute("voyager-desktop-sectionExpander-listener",function(a,f,b){function e(){if(!q){var d=document.getElementById("productDetails_expanderSectionTables");a.onScreen(d,0)&&(b.setCounter(b.metricName.impression(k,c),1),b.setCounter(b.metricName.impression("all","all"),1),q=!0)}}function d(){var d=document.getElementById("productDetails_expanderSectionTables");d&&a.onScreen(d,0)&&!document.hidden?
(e(),h&&function(){var d=Date.now()-h;p+=d;var e=f("#productDetails_expanderSectionTables").find(".a-expander-header");e&&e.length&&e.each(function(){if(a.onScreen(this,0)&&"true"===this.getAttribute("aria-expanded")){var e=JSON.parse(f(this).parent().attr("data-voyager-expander-heading-toggle")),g=e.columnName+e.sectionIndex;m.set(g,(m.get(g)||0)+d);b.setCounter(b.metricName.sectionExpanderContentDwellTime(k,c,e.columnName,e.sectionIndex+1),m.get(g));b.setCounter(b.metricName.sectionExpanderContentDwellTime("all",
"all",e.columnName,e.sectionIndex+1),m.get(g))}});b.setCounter(b.metricName.sectionExpanderContentOverallDwellTime(k,c),p);b.setCounter(b.metricName.sectionExpanderContentOverallDwellTime("all","all"),p)}(),h=Date.now()):h=n}var g=a.state("voyager-desktop-context"),c="unknown",k="unknown";g&&(c=g["voyager-desktop-treatment"],k=g.product_type);var m=new Map,h=void 0,p=0,q=!1;(function(){document.addEventListener("visibilitychange",function(){document.hidden&&(h=n)});d();a.interval(d,1E3)})();a.declarative("voyager-expander-heading-toggle",
"click",function(a){if(a&&a.data){d();var e=a.data.sectionIndex;a=a.data.columnName;"true"===f("#productDetails_expanderTables_"+a).find(".a-expander-header").eq(e).attr("aria-expanded")&&(b.incrementCounter(b.metricName.sectionExpanderClicked(k,c,a,e+1)),b.incrementCounter(b.metricName.sectionExpanderClicked("all","all",a,e+1)),b.incrementCounter(b.metricName.sectionExpanderOverallClicked(k,c)),b.incrementCounter(b.metricName.sectionExpanderOverallClicked("all","all")))}})});"use strict";"use strict";
"use strict";g.when("A").register("voyager-ns-desktop-side-sheet-ui",function(a){function e(c){var b=d("#a-page");b&&(b.removeAttr("inert",""),b.removeAttr("aria-hidden","true"));if(b=d("#navFooter"))b.removeAttr("inert",""),b.removeAttr("aria-hidden","true");if(b=d("#rhf"))b.removeAttr("inert",""),b.removeAttr("aria-hidden","true");c.$event.preventDefault();c.$event.stopPropagation();f();a.hide("#voyager-ns-desktop-dp-bg");d("body").css("overflow","scroll");(c=d(".voyager-ns-desktop-side-sheet-jump-link"))&&
0<c.length&&c.attr("aria-expanded","false")}function b(){d("#voyager-ns-desktop-side-sheet-container").show(function(){a.animate(d("#voyager-ns-desktop-side-sheet-container"),{right:"0px"},300,"ease-out",void 0)})}function f(){d("#voyager-ns-desktop-side-sheet-container").show(function(){a.animate(d("#voyager-ns-desktop-side-sheet-container"),{right:"-600px"},300,"ease-out",void 0)})}var d=a.$,g=!1;a.declarative("open-voyager-ns-desktop-side-sheet","click keydown",function(c){if("click"===c.type||
"keydown"===c.type&&(32===c.$event.keyCode||32===c.$event.key)){if(!g){g=!0;var e=d("\x3cdiv id\x3d'voyager-ns-desktop-dp-bg' class\x3d'a-section aok-hidden voyager-ns-desktop-darken-bg'\x3e\x3c/div\x3e"),f=d("\x3cspan class\x3d'a-declarative' data-action\x3d'close-voyager-ns-desktop-side-sheet' data-close-voyager-ns-desktop-side-sheet\x3d'{}'\x3e\x3c/span\x3e");e.appendTo(f);f.prependTo("body");d("#voyager-ns-desktop-side-sheet-container").length?(a.show("#voyager-ns-desktop-side-sheet-container"),
d("#voyager-ns-desktop-side-sheet-container").insertAfter(f)):a.hide(".voyager-ns-desktop-side-sheet-jump-link")}if(e=d("#a-page"))e.attr("inert",""),e.attr("aria-hidden","true");if(e=d("#navFooter"))e.attr("inert",""),e.attr("aria-hidden","true");if(e=d("#rhf"))e.attr("inert",""),e.attr("aria-hidden","true");c.$event.preventDefault();c.$event.stopPropagation();d("body").css("overflow","hidden");a.show("#voyager-ns-desktop-dp-bg");b();(c=d(".voyager-ns-desktop-side-sheet-jump-link"))&&0<c.length&&
d(".voyager-ns-desktop-side-sheet-jump-link").attr("aria-expanded","true");(c=d(".voyager-ns-desktop-side-sheet-close-button"))&&c.parent().focus()}});a.declarative("close-voyager-ns-desktop-side-sheet","click keydown",function(a){if("click"===a.type||"keydown"===a.type&&(13===a.$event.keyCode||13===a.$event.key))e(a),d(".voyager-ns-desktop-side-sheet-jump-link").focus();"keydown"!==a.type||9!==a.$event.keyCode&&9!==a.$event.key||!a.$event.shiftKey||(a.$event.preventDefault(),a.$event.stopPropagation())});
a.declarative("voyager-ns-desktop-close-on-esc-action","keydown",function(a){"keydown"!==a.type||27!==a.$event.keyCode&&27!==a.$event.key||(e(a),d(".voyager-ns-desktop-side-sheet-jump-link").focus())})});"use strict";"use strict"});