'use strict';mix_d("CustomerReviewsProductInsightsCards__cr-product-insights:cr-product-insights__fpZtkMT7","require exports tslib @c/scoped-dom @c/logger @c/metrics @c/browser-window @c/dom @c/browser-operations".split(" "),function(X,J,f,z,Y,Z,aa,K,ba){function w(c){return c&&"object"===typeof c&&"default"in c?c:{"default":c}}function ca(c){if(c&&c.__esModule)return c;var a=Object.create(null);c&&Object.keys(c).forEach(function(b){if("default"!==b){var d=Object.getOwnPropertyDescriptor(c,b);Object.defineProperty(a,
b,d.get?d:{enumerable:!0,get:function(){return c[b]}})}});a["default"]=c;return a}var l=w(z),L=w(Y),da=w(aa),M=w(K),ea=w(ba),k={isDesktopView:"_Y3Itc_is-desktop-view_29OYH",isMobileView:"_Y3Itc_is-mobile-view_2p4SJ",dataContainer:"_Y3Itc_data-container_2n3A8",contentContainer:"_Y3Itc_content-container_1EAqP",contentContainerPadding:"_Y3Itc_content-container-padding_66Xh7",contentContainerVerticalPadding:"_Y3Itc_content-container-vertical-padding_38N5b",sentimentSection:"_Y3Itc_sentiment-section_3Z0bO",
sentimentHeader:"_Y3Itc_sentiment-header_3nrex",sentimentAspects:"_Y3Itc_sentiment-aspects_2mp4b",aspectButtonGroup:"_Y3Itc_aspect-button-group_-biHO",aspectSymbolList:"_Y3Itc_aspect-symbol-list_24amT",insightBottomSheetButtonGroup:"_Y3Itc_insight-bottom-sheet-button-group_1gQMy",aspectList:"_Y3Itc_aspect-list_cBugj",aspectLink:"_Y3Itc_aspect-link_TtdmS",aspectLinkPill:"_Y3Itc_aspect-link-pill_1wnEf",aspectLinkSymbol:"_Y3Itc_aspect-link-symbol_23T9N",selected:"_Y3Itc_selected_2-xMA",underline:"_Y3Itc_underline_1Tba0",
subtitleAspectButton:"_Y3Itc_subtitle-aspect-button_2o27X",bottomSheetWrapper:"_Y3Itc_bottom-sheet-wrapper_PdjHu",hideBottomSheet:"_Y3Itc_hide-bottom-sheet_3ijux aok-hidden",insightBottomSheet:"_Y3Itc_insight-bottom-sheet_3SFlx",insightBottomSheetRedesign:"_Y3Itc_insight-bottom-sheet-redesign_1NP0A",insightBottomSheetContent:"_Y3Itc_insight-bottom-sheet-content_3cnVT",insightBottomSheetSubtitle:"_Y3Itc_insight-bottom-sheet-subtitle_28v47",endingLine:"_Y3Itc_ending-line_1I1OL",snippet:"_Y3Itc_snippet_2SpLd",
fragment:"_Y3Itc_fragment_tnwGQ",snippetSeeMore:"_Y3Itc_snippet-see-more_3qykv",statTextBox:"_Y3Itc_stat-text-box_8ba_x",statTextBoxRow:"_Y3Itc_stat-text-box-row_1_DtP",statTextBoxTitle:"_Y3Itc_stat-text-box-title_26C4y",statTextBoxSubtitle:"_Y3Itc_stat-text-box-subtitle_1wPSa",statCustomerMentionsBox:"_Y3Itc_stat-customer-mentions-box_Su4zw",statTextBoxLabelRow:"_Y3Itc_stat-text-box-label-row_3uYIE",statNumber:"_Y3Itc_stat-number_1J1Vr",statInfoBox:"_Y3Itc_stat-info-box_1akN2",closeButton:"_Y3Itc_close-button_qtNz0",
textPositive:"_Y3Itc_text-positive_QRaJ2",textNegative:"_Y3Itc_text-negative_zjq0Y",aspectSummaryLink:"_Y3Itc_aspect-summary-link_1Ls1M",aspectSummaryLabel:"_Y3Itc_aspect-summary-label_19a1a",productInsightsDivider:"_Y3Itc_product-insights-divider_3lxIJ",aiBrandingIcon:"_Y3Itc_ai-branding-icon_1_-VZ",aiIconLeft:"_Y3Itc_ai-icon-left_2U2uo",aiIconRight:"_Y3Itc_ai-icon-right_2svOG"},D={rendered:0,content:0,empty:0,"aspect-button-clicked":0,"aspect-button-dp-clicked":0,"aspect-button-bottomsheet-clicked":0,
"snippet-clicked":0,"aspects-scrolled":0,"bottomsheet-closed":0},t=function(c){var a,b=null!==(a=D[c])&&void 0!==a?a:0;D[c]=b+1;Z.count("cr-product-insights:dp:"+c,D[c])},N=function(c,a){if(c=l["default"].cardRoot.getElementsByClassName(c))for(var b=0;b<c.length;b++){var d=c[b];d&&d.addEventListener("click",function(){t(a)})}},x=function(c,a){c&&c.addEventListener("click",function(){t(a)})},fa=function(c,a){var b=l["default"].cardRoot.getElementsByClassName(c),d=Array(b.length);if(b){c=function(g){d[g]=
!1;var h=b[g];h&&h.addEventListener("scroll",function(){d[g]||(d[g]=!0,t(a))})};for(var e=0;e<b.length;e++)c(e)}},ha=function(){try{t("rendered");var c=l["default"].cardRoot.getElementsByClassName(k.contentContainer);t(0===c.length?"empty":"content");c&&(N(k.aspectButton,"aspect-button-clicked"),N(k.snippetSeeMore,"snippet-clicked"),fa(k.sentimentAspects,"aspects-scrolled"))}catch(a){}};z=function(){function c(){}c.prototype.show=function(){return f.__awaiter(this,void 0,void 0,function(){return f.__generator(this,
function(a){throw Error("not implemented");})})};c.prototype.hide=function(){return f.__awaiter(this,void 0,void 0,function(){return f.__generator(this,function(a){throw Error("not implemented");})})};c.prototype.updateContent=function(a){return f.__awaiter(this,void 0,void 0,function(){return f.__generator(this,function(b){throw Error("not implemented");})})};return c}();var ia=function(c){function a(b){var d=c.call(this)||this;b=d.getContentSelector(b.sentimentIndex);d.contentHTML=l["default"].cardRoot.querySelector("#"+
b);return d}f.__extends(a,c);a.prototype.show=function(){return f.__awaiter(this,void 0,void 0,function(){return f.__generator(this,function(b){this.contentHTML&&(this.contentHTML.style.display="block");return[2]})})};a.prototype.hide=function(){return f.__awaiter(this,void 0,void 0,function(){return f.__generator(this,function(b){this.contentHTML&&(this.contentHTML.style.display="none");return[2]})})};a.prototype.updateContent=function(b){return f.__awaiter(this,void 0,void 0,function(){return f.__generator(this,
function(d){this.hideAllContentList();this.showCurrentSelectedAspect(l["default"].cardRoot,b.aspectButtonsSize,b.aspectIndex,b.sentimentIndex);return[2]})})};a.prototype.getContentSelector=function(b){return"second-bottom-sheet-"+b};a.prototype.hideAllContentList=function(){l["default"].cardRoot.querySelectorAll("."+k.insightBottomSheetContent).forEach(function(b){b.style.display="none"})};a.prototype.showCurrentSelectedAspect=function(b,d,e,g){if(b=b.querySelector("#aspect-bottom-sheet-"+g+"-"+e))b.style.display=
"block"};return a}(z),O=function(c){function a(b){var d=c.call(this)||this;d.bottomSheetName=b.bottomSheetName;d.bottomSheetHTML=b.bottomSheetHTML;d.bottomSheet=b.bottomSheet;return d}f.__extends(a,c);a.build=function(b){return f.__awaiter(this,void 0,void 0,function(){var d,e,g,h;return f.__generator(this,function(m){switch(m.label){case 0:return[4,new Promise(function(n,r){X(["@c/aui-bottom-sheet"],function(p){n(ca(p))},r)})];case 1:return d=m.sent().default,e=this.getBottomSheetName(b.sentimentIndex),
g=M["default"].cardRoot.querySelector("#"+e),h=d.create(e,"#"+e,{height:da["default"].innerHeight*this.HEIGHT_PERCENTAGE}),h.on("afterHide",function(){h.render(function(n){a.hideAllBottomSheets(n,b.aspectBottomSheetCount,b.sentimentIndex)});t("bottomsheet-closed")}),[2,new a(f.__assign(f.__assign({},b),{bottomSheetName:e,bottomSheetHTML:g,bottomSheet:h}))]}})})};a.prototype.show=function(){return f.__awaiter(this,void 0,void 0,function(){return f.__generator(this,function(b){switch(b.label){case 0:return[4,
this.bottomSheet.show()];case 1:return b.sent(),[2]}})})};a.prototype.updateContent=function(b){return f.__awaiter(this,void 0,void 0,function(){var d=this;return f.__generator(this,function(e){switch(e.label){case 0:return[4,this.bottomSheet.render(function(g){return f.__awaiter(d,void 0,void 0,function(){var h,m,n,r;return f.__generator(this,function(p){switch(p.label){case 0:return this.showOnlySelectedBottomSheet(g,b.aspectButtonsSize,b.aspectIndex,b.sentimentIndex),[4,this.bottomSheet.show()];
case 1:return p.sent()&&(null===(n=null===(m=null===(h=K.unscope(g))||void 0===h?void 0:h.parentElement)||void 0===m?void 0:m.parentElement)||void 0===n?void 0:n.setAttribute("aria-label",null===(r=M["default"].cardRoot.querySelector("#product-summary h3"))||void 0===r?void 0:r.textContent)),[2]}})})})];case 1:return e.sent(),[2]}})})};a.getBottomSheetName=function(b){return"second-bottom-sheet-"+b};a.prototype.showOnlySelectedBottomSheet=function(b,d,e,g){for(var h=0;h<d;h++){var m=b.querySelector("#aspect-bottom-sheet-"+
g+"-"+h);m&&(m.style.display=h===e?"block":"none")}};a.hideAllBottomSheets=function(b,d,e){for(var g=0;g<d;g++){var h=b.querySelector("#aspect-bottom-sheet-"+e+"-"+g);h&&(h.style.display="none")}};a.HEIGHT_PERCENTAGE=.85;return a}(z),u=function(c,a,b){var d=ea["default"].setup(),e=d.define;d=d.attach;e(a,"click",b);c.addEventListener("keydown",function(g){var h,m;switch(g.key){case " ":g.preventDefault();c.click();break;case "ArrowLeft":g.preventDefault();(c.previousSibling||(null===(h=c.parentNode)||
void 0===h?void 0:h.lastChild)).focus();break;case "ArrowRight":g.preventDefault(),(c.nextSibling||(null===(m=c.parentNode)||void 0===m?void 0:m.firstChild)).focus()}});d(a,c)},y=function(c,a,b){void 0===b&&(b=!0);for(var d=0;d<a.length;d++){var e=a[d];e.classList.contains(k.selected)&&b&&e.classList.remove(k.selected);e.setAttribute("aria-selected","false");e.setAttribute("tabindex","-1")}b&&c.classList.add(k.selected);c.setAttribute("aria-selected","true");c.setAttribute("tabindex","0")},P=function(){function c(a){var b=
a.sentimentHTML,d=a.aspectButtons,e=a.aspectButtonsInBottomSheet,g=a.updater;this.sentimentIndex=a.sentimentIndex;this.sentimentHTML=b;this.aspectButtons=d;this.aspectButtonsInBottomSheet=e;this.updater=g}c.build=function(a){var b=a.sentimentIndex,d=a.sentimentHTML;return f.__awaiter(this,void 0,void 0,function(){var e,g,h;return f.__generator(this,function(m){switch(m.label){case 0:return e=this.getAspectButtons(d,b),g=this.getAspectButtonsInBottomSheet(b),[4,O.build({aspectBottomSheetCount:g.length,
sentimentIndex:b})];case 1:return h=m.sent(),[2,new c({sentimentIndex:b,sentimentHTML:d,aspectButtons:e,aspectButtonsInBottomSheet:g,updater:h})]}})})};c.prototype.bind=function(){this.bindEventForButtonGroupInFirstPage();this.bindEventForButtonGroupInBottomSheet();this.bindEventTracking()};c.getAspectButtonsInBottomSheet=function(a){return(a=l["default"].cardRoot.querySelector("#second-bottom-sheet-"+a))?(a=a.querySelector("."+k.insightBottomSheetButtonGroup),Array.from(a.querySelectorAll("."+k.aspectLink))):
[]};c.getAspectButtons=function(a,b){return(a=a.querySelector("#aspect-button-group-"+b))?Array.from(a.querySelectorAll("."+k.aspectLink)):[]};c.prototype.bindEventForButtonGroupInFirstPage=function(){var a=this;this.aspectButtons.forEach(function(b,d){u(b,b.id,function(){return f.__awaiter(a,void 0,void 0,function(){var e;return f.__generator(this,function(g){switch(g.label){case 0:e=this.aspectButtonsInBottomSheet[d];if(!e)return[3,2];this.updateSelectedAspectButton(e,this.aspectButtonsInBottomSheet);
y(this.aspectButtons[d],this.aspectButtons,!1);return[4,this.updater.updateContent({aspectButtonsSize:this.aspectButtonsInBottomSheet.length,aspectIndex:d,sentimentIndex:this.sentimentIndex})];case 1:g.sent(),g.label=2;case 2:return e&&e.scrollIntoView({behavior:"smooth",inline:"center",block:"nearest"}),[2]}})})})})};c.prototype.bindEventForButtonGroupInBottomSheet=function(){var a=this;this.aspectButtonsInBottomSheet.forEach(function(b,d){u(b,b.id,function(){return f.__awaiter(a,void 0,void 0,function(){return f.__generator(this,
function(e){switch(e.label){case 0:return this.updateSelectedAspectButton(b,this.aspectButtonsInBottomSheet),y(this.aspectButtons[d],this.aspectButtons,!1),[4,this.updater.updateContent({aspectButtonsSize:this.aspectButtonsInBottomSheet.length,aspectIndex:d,sentimentIndex:this.sentimentIndex})];case 1:return e.sent(),[2]}})})})})};c.prototype.bindEventTracking=function(){this.aspectButtons.forEach(function(a){x(a,"aspect-button-dp-clicked")});this.aspectButtonsInBottomSheet.forEach(function(a){x(a,
"aspect-button-bottomsheet-clicked")})};c.prototype.updateSelectedAspectButton=function(a,b){y(a,b)};return c}(),ja=function(){function c(a){var b=a.sentimentHTML,d=a.aspectButtons,e=a.updater,g=a.asin;this.sentimentIndex=a.sentimentIndex;this.sentimentHTML=b;this.aspectButtons=d;this.updater=e;this.asin=g}c.build=function(a){var b=a.sentimentIndex,d=a.sentimentHTML,e=a.asin;return f.__awaiter(this,void 0,void 0,function(){var g,h;return f.__generator(this,function(m){g=this.getAspectButtons(d,b);
h=new ia({sentimentIndex:b});return[2,new c({sentimentIndex:b,sentimentHTML:d,aspectButtons:g,asin:e,updater:h})]})})};c.prototype.bind=function(){var a=this;this.aspectButtons.forEach(function(b,d){u(b,b.id,function(){return f.__awaiter(a,void 0,void 0,function(){return f.__generator(this,function(e){switch(e.label){case 0:return[4,this.onClick(b,d)];case 1:return e.sent(),[2]}})})});a.fetchPreviousStateOfButton(d,b)});this.bindEventTracking();this.bindEventSeeMoreButtons();this.bindCloseButtons()};
c.prototype.bindEventSeeMoreButtons=function(){var a=this;l["default"].cardRoot.querySelectorAll("."+k.snippetSeeMore).forEach(function(b){b.addEventListener("click",function(){a.seeMoreStateToSessionStorage()})})};c.prototype.onClick=function(a,b){return f.__awaiter(this,void 0,void 0,function(){return f.__generator(this,function(d){switch(d.label){case 0:if(!a.classList.contains(k.selected))return[3,2];a.classList.remove(k.selected);return[4,this.updater.hide()];case 1:return d.sent(),this.resetStateInSessionStorage(),
[3,5];case 2:return this.updateSelectedAspectButton(a),[4,this.updater.updateContent({aspectButtonsSize:this.aspectButtons.length,aspectIndex:b,sentimentIndex:this.sentimentIndex})];case 3:return d.sent(),[4,this.updater.show()];case 4:d.sent(),this.saveStateToSessionStorage(b,this.sentimentIndex),d.label=5;case 5:return[2]}})})};c.prototype.bindCloseButtons=function(){return f.__awaiter(this,void 0,void 0,function(){var a,b=this;return f.__generator(this,function(d){a=l["default"].cardRoot.querySelectorAll("."+
k.closeButton);a.forEach(function(e){u(e,e.id,function(){b.updater.hide();b.resetAllAspectButtons();b.aspectButtons[parseInt(e.getAttribute("data-aspect-index")||"0")].focus()})});return[2]})})};c.prototype.fetchPreviousStateOfButton=function(a,b){this.isSelectedAspect(a)&&(this.updater.updateContent({aspectButtonsSize:this.aspectButtons.length,aspectIndex:a,sentimentIndex:this.sentimentIndex}),this.updateSelectedAspectButton(b))};c.getAspectButtons=function(a,b){return(a=a.querySelector("#aspect-button-group-"+
b))?Array.from(a.querySelectorAll("."+k.aspectLink)):[]};c.prototype.resetAllAspectButtons=function(){var a=l["default"].cardRoot.querySelectorAll("."+k.aspectLink);a=Array.from(a);for(var b=0;b<a.length;b++){var d=a[b];d.classList.contains(k.selected)&&d.classList.remove(k.selected)}};c.prototype.bindEventTracking=function(){this.aspectButtons.forEach(function(a){x(a,"aspect-button-dp-clicked")})};c.prototype.updateSelectedAspectButton=function(a){this.resetAllAspectButtons();y(a,this.aspectButtons)};
c.prototype.saveStateToSessionStorage=function(a,b){sessionStorage.setItem("productInsights",JSON.stringify({selectedAspectId:a,selectedSentimentId:b,currentAsin:this.asin}))};c.prototype.seeMoreStateToSessionStorage=function(){sessionStorage.setItem("productInsightsSeeMoreClick",JSON.stringify({isClick:!0,asin:this.asin}))};c.prototype.resetStateInSessionStorage=function(){sessionStorage.removeItem("productInsights")};c.prototype.isSelectedAspect=function(a){var b=sessionStorage.getItem("productInsights");
if(null==b)return!1;var d=JSON.parse(b);b=d.selectedAspectId;var e=d.selectedSentimentId;d=d.currentAsin;return null===b||null===e||null===d?!1:d===this.asin&&parseInt(b)===a&&parseInt(e)===this.sentimentIndex};return c}(),ka=function(){function c(a){var b=a.aspectBottomSheetButtons,d=a.updater,e=a.sentimentIndex;this.aspectLinks=a.aspectLinks;this.aspectBottomSheetButtons=b;this.updater=d;this.sentimentIndex=e}c.build=function(a){var b=a.aspectLinks,d=a.aspectBottomSheetButtons,e=a.sentimentIndex;
return f.__awaiter(this,void 0,void 0,function(){var g;return f.__generator(this,function(h){switch(h.label){case 0:return[4,O.build({aspectBottomSheetCount:d.length,sentimentIndex:e})];case 1:return g=h.sent(),[2,new c({aspectLinks:b,aspectBottomSheetButtons:d,updater:g,sentimentIndex:e})]}})})};c.prototype.bindEventForLinksInFirstPage=function(){var a=this;this.aspectLinks.forEach(function(b){var d=b.id.split("-")[3],e=a.aspectBottomSheetButtons[d];u(b,b.id,function(){return f.__awaiter(a,void 0,
void 0,function(){return f.__generator(this,function(g){switch(g.label){case 0:return this.updateSelectedAspectButton(e,this.aspectBottomSheetButtons),[4,this.updater.updateContent({aspectButtonsSize:this.aspectBottomSheetButtons.length,aspectIndex:+d,sentimentIndex:this.sentimentIndex})];case 1:return g.sent(),e&&e.scrollIntoView({behavior:"smooth",inline:"center",block:"nearest"}),[2]}})})})})};c.prototype.bindEventForButtonGroupInBottomSheet=function(){var a=this;this.aspectBottomSheetButtons.forEach(function(b,
d){u(b,b.id,function(){return f.__awaiter(a,void 0,void 0,function(){return f.__generator(this,function(e){switch(e.label){case 0:return this.updateSelectedAspectButton(b,this.aspectBottomSheetButtons),[4,this.updater.updateContent({aspectButtonsSize:this.aspectBottomSheetButtons.length,aspectIndex:d,sentimentIndex:this.sentimentIndex})];case 1:return e.sent(),[2]}})})})})};c.prototype.bind=function(){this.bindEventForLinksInFirstPage();this.bindEventForButtonGroupInBottomSheet();this.bindEventTracking()};
c.prototype.bindEventTracking=function(){this.aspectLinks.forEach(function(a){x(a,"aspect-link-dp-clicked")});this.aspectBottomSheetButtons.forEach(function(a){x(a,"aspect-button-bottomsheet-clicked")})};c.prototype.updateSelectedAspectButton=function(a,b){y(a,b)};return c}(),la=function(){var c=l["default"].cardRoot.querySelector("#summary-disclaimer-title-container"),a=l["default"].cardRoot.querySelector("#summary-disclaimer-title"),b=l["default"].cardRoot.querySelector("#ai-icon-left"),d=l["default"].cardRoot.querySelector("#ai-icon-right");
if(c&&a&&b&&d){var e=a.textContent||"";if(e.startsWith("AI")){var g=e.substring(2);var h="left"}else e.endsWith("AI")?(g=e.substring(0,e.length-2),h="right"):(g=e,h="left");c.setAttribute("aria-label",e);a.textContent=g;"left"===h?(b.style.display="inline-block",d.style.display="none"):(b.style.display="none",d.style.display="inline-block")}},ma=function(c){var a=sessionStorage.getItem("productInsightsSeeMoreClick");if(null==a)c=!1;else{a=JSON.parse(a);var b=a.isClick;c=a.asin===c&&!!b}c&&(c=l["default"].cardRoot.querySelectorAll("."+
k.contentContainer),0<c.length&&(c[0].scrollIntoView({block:"center",inline:"center"}),sessionStorage.removeItem("productInsightsSeeMoreClick")))},oa=function(){return f.__awaiter(void 0,void 0,void 0,function(){var c,a,b,d,e,g,h,m,n,r,p,v,E,F,Q,R,S,T,U,G,V,H,I;return f.__generator(this,function(q){switch(q.label){case 0:q.trys.push([0,10,,11]);c=k.bottomSheetWrapper.split(" ")[0];a=l["default"].cardRoot.getElementsByClassName(c)[0];b=0<l["default"].cardRoot.getElementsByClassName(k.isDesktopView).length;
d=function(){return l["default"].cardRoot.getElementsByClassName(k.contentContainer)[0]};e=b?null!==(I=null===(H=d())||void 0===H?void 0:H.dataset.asin)&&void 0!==I?I:"":"";if(!a)return[3,9];g=l["default"].cardRoot.querySelectorAll("."+k.sentimentSection);g.forEach(function(A,W){return f.__awaiter(void 0,void 0,void 0,function(){var B;return f.__generator(this,function(C){switch(C.label){case 0:return b?[4,ja.build({sentimentHTML:A,sentimentIndex:W,asin:e})]:[3,2];case 1:return B=C.sent(),B.bind(),
[3,4];case 2:return[4,P.build({sentimentHTML:A,sentimentIndex:W})];case 3:B=C.sent(),B.bind(),C.label=4;case 4:return[2]}})})});h=l["default"].cardRoot.querySelectorAll("#product-summary");m=0<h.length;if(!m)return[3,9];n=l["default"].cardRoot.querySelectorAll("."+k.aspectSummaryLink);r=na(n);q.label=1;case 1:q.trys.push([1,6,7,8]),p=f.__values(r),v=p.next(),q.label=2;case 2:if(v.done)return[3,5];E=f.__read(v.value,2);F=E[0];Q=E[1];R=P.getAspectButtonsInBottomSheet(F);return[4,ka.build({aspectLinks:Q,
aspectBottomSheetButtons:R,sentimentIndex:F})];case 3:S=q.sent(),S.bind(),q.label=4;case 4:return v=p.next(),[3,2];case 5:return[3,8];case 6:return T=q.sent(),G={error:T},[3,8];case 7:try{v&&!v.done&&(V=p.return)&&V.call(p)}finally{if(G)throw G.error;}return[7];case 8:try{la()}catch(A){L["default"].log("Product Insight: Error setting up AI branding icon: "+A.message,"ERROR")}q.label=9;case 9:return b&&ma(e),ha(),[3,11];case 10:return U=q.sent(),L["default"].log("Product Insight: Error:"+U.message,
"ERROR"),[3,11];case 11:return[2]}})})},na=function(c){var a=new Map;c.forEach(function(b){var d=+b.id.split("-")[2];a.has(d)||a.set(d,[]);a.get(d).push(b)});return a};J._operationNames=[];J.card=function(){return f.__awaiter(void 0,void 0,void 0,function(){return f.__generator(this,function(c){switch(c.label){case 0:return[4,oa()];case 1:return[2,c.sent()]}})})}});
