window.aui.amd_define("@amzn/kata-web-framework-logger",["exports"],function(r){"use strict";const l=()=>{var n;return(n=!1)!==null&&n!==void 0?n:!1},d=()=>!0,g=()=>window.ueLogError,m=n=>console[n];function t({code:n,e:o,context:e,level:w="ERROR"}){const u=g(),c=m(E[w]);if(u&&d()){const i={logLevel:w,attribution:"HtmlKataWebFrameworkJs",message:n};o instanceof Error?u(o,i):u(i),l()&&c(n,o,{...i,...e})}else l()?c(n,o,e):c(n,o)}const E={FATAL:"error",ERROR:"error",WARN:"warn"},b=(n,o,e)=>{t({code:n,e:o,context:e,level:"ERROR"})},a=(n,o,e)=>{t({code:n,e:o,context:e,level:"WARN"})},I=(n,o,e)=>{t({code:n,e:o,context:e,level:"FATAL"})},L=()=>{},R=(n,o,e)=>{o.has(n)?a(e):o.add(n)};let f=!1;const s=()=>window.fm?window.fm:(f||(a("K067"),f=!0),{recordInstrumentationEvent:()=>{},now:()=>0});function v(n,o){const e=s();e.recordInstrumentationEvent(n,o!=null?o:e.now())}const A=()=>typeof window.uex!="function"?()=>{}:window.uex,K=()=>!window.ue||typeof window.ue.count!="function"?()=>{}:window.ue.count;function k(){A()("ld","kwf",{wb:1})}function y(){K()("kwf.enabled",1)}r.countKwfEnabled=y,r.error=b,r.fatal=I,r.fmInstance=s,r.log=t,r.recordMetric=v,r.reportKwfLoaded=k,r.timing=L,r.warn=a,r.warnIfDuplicate=R,Object.defineProperty(r,Symbol.toStringTag,{value:"Module"})});/*! _CB1_ */

/* ******** */
window.aui.amd_define("@amzn/kata-web-framework-register",["exports","@amzn/kata-web-framework-logger"],function(o,u){"use strict";const t=Object.create(null),R=(e,r)=>{var l;return t[e]=(l=t[e])!==null&&l!==void 0?l:B(r,e),t[e].config!==r&&u.log({code:"K031",context:{uuid:e,config:r}}),t[e]},f=(e,...r)=>R(K(e,...r),e),B=(e,r)=>{let l,s,a=!1,n;const w=i=>{var m,v,c;if(l){u.warn((m=e.diagnostics.alreadyProvidedWarn)!==null&&m!==void 0?m:"K005",null,{uuid:r});return}if(s){u.warn((v=e.diagnostics.alreadyFailedWarn)!==null&&v!==void 0?v:"K006",null,{uuid:r});return}if(a){u.warn((c=e.diagnostics.alreadyReleasedWarn)!==null&&c!==void 0?c:"K009",null,{uuid:r});return}i()},k=i=>{w(()=>{l=i})},P=i=>{w(()=>{s=i})},p=()=>{a||(n=void 0,l=void 0,s=void 0,a=!0)},T={uuid:r,provide:k,fail:P,release:p,assertReleased:()=>{if(!a&&!e.willNotBeReleased)throw new Error("K057")},promise:()=>(n||(s?n=Promise.reject(s):l?n=Promise.resolve(l):a?n=Promise.reject(new Error("K058")):n=new Promise((i,m)=>{const v=M(e,r),c=()=>{v.forEach(d=>clearTimeout(d))};T.provide=d=>{k(d),i(d),c()},T.fail=d=>{P(d),m(d),c()},T.release=()=>{p(),m(new Error("K058")),c()}})),e.singleConsumer&&(n=n.finally(p)),n),config:e};return T},K=(e,...r)=>`${e.namespace}:${r.join(",")}`,g=e=>{for(const r of e)t[r]&&t[r].release()},j=e=>{for(const r in t){const l=r;e&&t[l].assertReleased(),t[l].release(),delete t[l]}},E=3e3,C=3e4,M=({timeouts:e,diagnostics:r},l)=>{var s,a;const n=setTimeout(()=>{u.warn(r.timeout,null,{uuid:l})},(s=e==null?void 0:e.warn)!==null&&s!==void 0?s:E),w=setTimeout(()=>{u.error(r.timeout,null,{uuid:l})},(a=e==null?void 0:e.error)!==null&&a!==void 0?a:C);return[n,w]},y={namespace:"ext",diagnostics:{timeout:"K059"},willNotBeReleased:!0},_={namespace:"template",diagnostics:{timeout:"K001"},willNotBeReleased:!0},N=(e,r)=>f(_,e).provide(r),b=e=>f(_,e).promise(),h=(e,r)=>f(y,e).provide(r),z=e=>f(y,e).promise();o.createUuid=K,o.externalLookup=z,o.externalRegister=h,o.lookup=b,o.register=N,o.release=g,o.track=R,o.trackByIds=f,o.unsafeReleaseAll=j,Object.defineProperty(o,Symbol.toStringTag,{value:"Module"})});/*! _CB1_ */

/* ******** */
window.aui.amd_define("@amzn/kata-web-framework-runtime-functions",["@amzn/kata-web-framework-runtime-utils"],function(n){"use strict";const t=()=>{},e=i=>i;return()=>({unsupportedFn:n.unsupportedFn,voidFn:t,identityFn:e})});/*! _CB1_ */

/* ******** */
window.aui.amd_define("@amzn/kata-web-framework-runtime-utils",["exports","@amzn/kata-web-framework-logger"],function(n,t){"use strict";const c=(...r)=>r.flat(1/0).join(""),s=(...r)=>r.join(" ").trim().replace(/\s+/g," "),u=(r,e)=>(r%e+e)%e,l=(r,e)=>({get:()=>r.read(e),set:i=>{r.defer(()=>{try{r.write(e,i)}catch(g){t.error("K063",g,{value:e,newValue:i})}})}}),f=(r,e)=>({get:()=>r,set:e}),m=r=>({discriminator:o(r),value:r,reflection:typeof r}),o=r=>{var e;return(e=r==null?void 0:r.__type)!==null&&e!==void 0?e:r==null?void 0:r.runtimeDataType},y=(r,e)=>e.map(i=>`${i}=${a(r,i)}`).join("&"),a=(r,e)=>{switch(e){case"discriminator":return o(r);case"value":return r;case"reflection":return typeof r;case"length":return Array.isArray(r)?r.length:null}},d=()=>{t.error("K041")};n.box=l,n.classes=s,n.describeExpr=y,n.discriminators=m,n.flattenToString=c,n.mod=u,n.reBox=f,n.unsupportedFn=d,Object.defineProperty(n,Symbol.toStringTag,{value:"Module"})});/*! _CB1_ */

/* ******** */
